name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: 'temp-source'
        
      - name: Clean workspace
        run: |
          # 清除当前目录内容（保留.git目录）
          shopt -s extglob
          rm -rf !(.git)
          
      - name: Clone PhiCommunity repository
        run: git clone https://github.com/MoeFurina/PhiCommunity.git ./docs
          
      - name: Setup Node.js with pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
