name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: 'temp-source'  # 先检出到子目录
        
      - name: Clone PhiCommunity repository
        run: |
          rm -rf * .[!.]*  # 清除当前目录内容（除了.git目录）
          git clone https://github.com/MoeFurina/PhiCommunity.git .
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install pnpm
        run: npm install -g pnpm
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build project
        run: pnpm build
        
      - name: Move dist contents to root
        run: |
          # 备份克隆的仓库内容（如果需要）
          mkdir -p original-source
          cp -a !(original-source|temp-source) original-source/
          
          # 恢复我们自己的源文件
          cp -a temp-source/.github ./
          
          # 移动 dist 目录内容到根目录
          cp -a dist/. .
          
          # 清理不需要的目录
          rm -rf dist original-source temp-source
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
